apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '{{ (parameters.repoName | lower | replaceAll " " "-" | replaceAll "_" "-" ) }}'
  description: Sample service created from Backstage template
  tags:
    - sample
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
