apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.repoName | lower | replace(/[^a-z0-9-_.]/g, '') }}
  description: Sample service created from Backstage template
  tags:
    - sample
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
